import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/mainNavbar";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased")}>
        <div vaul-drawer-wrapper="">
          <Navbar />
          <div className="relative max-w-screen-2xl flex min-h-screen  flex-col bg-background">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
