
'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import AdminSidebar from "@/components/adminsidebar";
import AdminNavbar from "@/components/adminNav";
import { NotificationProvider } from "../context/NotificationContext";
import { cn } from "@/lib/utils";
import { useState } from "react";




// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
//   };
  
  export default function AdminLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {

    const [isVisible,setSisVisible] = useState(false)

    const toggleShowSideBar = ()=>{
      console.log('cliecked');
      
      setSisVisible((pre) => !pre)
    }
 
    return (
      <html lang="en">
        <body className={cn("min-h-screen bg-background font-sans antialiased")} >
          <NotificationProvider>
          <div vaul-drawer-wrapper="">
            <AdminNavbar toggleShowSideBar={toggleShowSideBar} />
            <AdminSidebar isVisible={isVisible} />
            <div className="relative max-w-screen-2xl flex min-h-screen  flex-col bg-background">
              {children}
            </div>
          </div>

          </NotificationProvider>
        </body>
      </html>
    );
  }
  